# Generated by Django 2.2.2 on 2020-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemmlWebUi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='', max_length=70)),
                ('project_date', models.CharField(default='', max_length=200)),
                ('project_config', models.BooleanField(default=False)),
            ],
        ),
    ]
