# Generated by Django 2.2.2 on 2020-06-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemml_web_ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemmlwebui',
            old_name='description',
            new_name='project_date',
        ),
        migrations.RenameField(
            model_name='chemmlwebui',
            old_name='title',
            new_name='project_title',
        ),
        migrations.RemoveField(
            model_name='chemmlwebui',
            name='published',
        ),
    ]
